version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/GTD-Visualization

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn && npm install xvfb-maybe

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      # run tests!
      - run: ./node_modules/.bin/xvfb-maybe node_modules/.bin/karma start test/unit/karma.conf.js && yarn run pack && ./node_modules/.bin/xvfb-maybe node_modules/.bin/mocha test/e2e
